### ISSUE TITLE
在英文版本vscode里面无法翻译，请修复

### ISSUE THREAD

**Issue by hellojer** [qq34347476/web#1]
我使用英文版本vscode发现无法翻译，中文版本目前还没测试。

![](http://img01.kumiao.net/2019/QQ浏览器截图20190730082628.png)

**Comment by qq34347476** [comment]
> 我使用英文版本vscode发现无法翻译，中文版本目前还没测试。
> 
> ![](https://camo.githubusercontent.com/6fe07d0ac886aa81ff6aa4417e34ccb3a1edfc81/687474703a2f2f696d6730312e6b756d69616f2e6e65742f323031392f515125453625423525384625453825413725383825453525393925413825453625383825414125453525394225424532303139303733303038323632382e706e67)

先选择语言，在翻译啊
