### ISSUE TITLE
jQuery语法

### ISSUE THREAD

**Issue by HuanYuanHe** [qq34347476/web#3]
在jQuery中
$.ajax({
            type: "GET",  //默认get
            url: "url",  //默认当前页
            data: "data",  //格式{key:value}
            dataType: "json",
            beforeSend: function () {}, //请求发送前回调,常用验证
            success: function (response) {  //请求成功回调      
            },
data的格式修改成：
 data:{"data“} ，默认为json格式是否更合理呢

**Comment by qq34347476** [comment]
jquery 语法已不再维护，工作中用到的不是很多= =。
