### ISSUE TITLE
希望能添加其他语言模板

### ISSUE THREAD

**Issue by a1156883061** [qq34347476/web#4]
在 Javascript react不能使用js的模板，希望可以设置关联的语言模式或者添加语言模式

**Comment by qq34347476** [comment]
react 有初始模板，! 可以调出

**Comment by qq34347476** [comment]
> 在JavaScript react无法使用js的模板，希望可以设置关联的语言模式或添加语言模式

react-native代码段已经加入(仅支持jsx])，js代码段 已支持.jsx
